### ISSUE TITLE
AndroidKeyStore的问题

### ISSUE THREAD

**Issue by DiamondProx** [Tencent/soter#14]
我看到代码里面有用到AndroidKeyStore，AndroidKeyStore里秘钥是否在TEE里面操作和存储，手机Root之后是否存在会被获取到的风险？(6.0之前或者6.0之后)

**Comment by yexuan910812** [comment]
所有通过Soter认证的机器都必须有TEE存储。无论是6.0之前还是6.0之后，支持SOTER的机器都不会有root后被获取密钥的风险
