### ISSUE TITLE
errCode=14？是什么意思

### ISSUE THREAD

**Issue by zbyJade** [Tencent/soter#19]
SoterCoreResult{errCode=14, errMsg='not initialized yet. please make sure you've already called SoterWrapperApi.init(...) and call backed'}
请问errcode ==14是什么意思，这是什么情况呢

**Comment by yexuan910812** [comment]
可以参考https://github.com/Tencent/soter/blob/master/soter-client-sdk/soter-wrapper/src/main/java/com/tencent/soter/wrapper/wrap_core/SoterProcessErrCode.java ，这里14的意思是没有调用过SoterWrapperApi.init 就进行了其他Soter调用操作
