### ISSUE TITLE
请教一个问题 有些地方用AndroidKeyStore 有些地方用SoterKeyStore 这两者的关系是?

### ISSUE THREAD

**Issue by GilBert1987** [Tencent/soter#2]
Hi 您好，
学习了soter 的代码，有一个疑问?
为啥 有些地方用AndroidKeyStore 有些地方用SoterKeyStore 这两者的关系是?

**Comment by yexuan910812** [comment]
我们希望密钥管理（如密钥的删除等）使用Android原生接口实现。这不仅仅是因为无需实现额外接口，也是因为贴近原生，后续Android升级这一模块不会产生兼容性问题。整个密钥管理体系的原则之一就是尽量贴近原生。当然，类似密钥生成和使用这种没办法和原生兼容的情况，还是不得不用自有的provider。

**Comment by GilBert1987** [comment]
嗯，感谢回复，AndroidKeyStore 好像不支持单独的密钥删除。

**Comment by yexuan910812** [comment]
支持密钥删除，或者说这个和AndroidKeystoreProvider关系不大，直接deleteEntry就好
