### ISSUE TITLE
能对一些错误码进行一些说明吗？有些问题如：ERR_ADD_TASK_FAILED不知道发生了什么

### ISSUE THREAD

**Issue by LazyDemo** [Tencent/soter#21]

**Comment by yexuan910812** [comment]
请参考 SoterProcessErrCode 以及其基类. https://github.com/Tencent/soter/blob/master/soter-client-sdk/soter-wrapper/src/main/java/com/tencent/soter/wrapper/wrap_core/SoterProcessErrCode.java
