### ISSUE TITLE
指纹认证之前生成相关密钥的问题

### ISSUE THREAD

**Issue by willsame** [Tencent/soter#22]
想问下，这个密钥怎么生成的?
SoterWrapperApi.prepareAuthKey(new SoterProcessCallback<SoterProcessKeyPreparationResult>() {...},false, true, 0, null, null);
这个api不太懂，求教，非常感谢

**Comment by wendydhwang** [comment]
可以查看sdk源码，也有文档说明:

SoterWrapperApi.prepareAuthKey(new SoterProcessCallback<SoterProcessKeyPreparationResult>() {...}, // 生成结果回调
    false,  // 已有AuthKey的话是否重新生成
    true,   // 如果没有ASK，是否一并生成
    ConstantsSoterDemo.SCENE_PAYMENT, // 本次密钥生成所使用业务的场景值，需要在init时填入
    new IWrapUploadKeyNet(pwdDigest){...}, // 上传AuthKey的NetWrapper
    new IWrapUploadKeyNet()){...}; // 上传ASK的NetWrapper

**Comment by yexuan910812** [comment]
Seems the problem has already been solved.
