### ISSUE TITLE
SoterWrapperApi.requestAuthorizeAndSign如何签名本地业务数据？

### ISSUE THREAD

**Issue by NSLog-newbird** [Tencent/soter#29]
SoterWrapperApi.requestAuthorizeAndSign如何签名本地业务数据？没有找到上传业务数据给TEE的接口，如何拿到最终的签名数据上传给自己的服务器验签呢？

**Comment by yexuan910812** [comment]
这里需要签什么业务数据呢？这个接口主要适用于签名挑战因子的。如果有需要的话，可以将业务数据作为challenge的一部分
