### ISSUE TITLE
支付Demo在华为MATE10 android P 上提示设备不支持

### ISSUE THREAD

**Issue by Likeyong** [Tencent/soter#30]
SoterCoreResult{errCode=2, errMsg='device not support soter'}
但是手机可以在微信里面使用指纹支付.
想问一下是微信支付做了特殊处理是吗

**Comment by Lindroy** [comment]
小米8se和华为荣耀V9遇到同样的问题。

**Comment by quhanglang** [comment]
小米6x也遇到这样的问题 android 8.1 可以正常运行，升级到android 9就提示不支持

**Comment by yexuan910812** [comment]
请升级到2.0
