### ISSUE TITLE
关于人脸识别如何实现的问题

### ISSUE THREAD

**Issue by whytot** [Tencent/soter#46]
尊敬的开发者们好！
我在做人脸识别时，没有找到关于Soter中人脸识别是如何实现的文档。源码中只有一段通过反射获取FaceManager的代码，但类名（com.tencent.soter.core.biometric.SoterFaceManagerFactory）看上并不是原生的。
在我找到的可以使用Soter调用人脸识别的设备上，没有办法通过系统原生的方式调用人脸识别，我想知道Soter是获取了系统/设备的特殊支持所以才可以实现人脸识别吗？能说明一下如何实现的吗？

**Comment by liuxb-tofu** [comment]
这里是要跟厂商合作实现的，厂商会提前植入我们的sdk，这样我们才能反射到对应的类

**Comment by whytot** [comment]
> 这里是要跟厂商合作实现的，厂商会提前植入我们的sdk，这样我们才能反射到对应的类
谢谢
