### ISSUE TITLE
Demo运行失败原因

### ISSUE THREAD

**Issue by qaz349293703** [Tencent/soter#5]
请问下，Application的初始化处，该处的Log打印的结果为
``soterdemo: get is support soter done. result: SoterCoreResult{errCode=2, errMsg=''}``是说明我这个机型不支持soter吗？

```
private SoterProcessCallback<SoterProcessNoExtResult> mGetIsSupportCallback = new SoterProcessCallback<SoterProcessNoExtResult>() {
        @Override
        public void onResult(@NonNull SoterProcessNoExtResult result) {
            DemoLogger.d(TAG, "soterdemo: get is support soter done. result: %s", result.toString());
            // 建议尽早准备ASK。主要有两个时机：1. 进程初始化时 2. 第一次使用业务任何一个业务时。这里在程序进程初始化的时候准备 ASK

            if(result.errCode == SoterProcessErrCode.ERR_OK) {
                prepareASK();
            }
        }
    };
```

**Comment by yexuan910812** [comment]
SoterCoreResult的结果可以在SoterErrCode里边看到。这里ErrString是空应该是有bug，下版本修复下。

 /**
     * Not support SOTER. You should check the support state before calling this method
     */
    int ERR_SOTER_NOT_SUPPORTED = 2;

支持的设备列表见这里https://mp.weixin.qq.com/s/IRI-RCGsVB2WiPwUCGcytA

**Comment by yexuan910812** [comment]
已在新版本1.3.8.1中修复 @qaz349293703
