### ISSUE TITLE
如何做屏下指纹的适配（像微信一样）

### ISSUE THREAD

**Issue by zhuimengxiaole** [Tencent/soter#51]
在有屏下指纹的手机，会调起系统提供的指纹界面，有提供修改界面的方法吗？可以做到带自己的业务UI，像微信指纹支付一样（PS：能说说微信实现的思路吗）

**Comment by liuxb-tofu** [comment]
[SoterExParameters](soter-client-sdk/soter-core/src/main/java/com/tencent/soter/core/model/SoterExParameters.java)，这个是获取屏下指纹位置的接口，但目前不是所有厂商都能获取，至于关掉系统的指纹界面，需要App跟厂商沟通。

**Comment by zhuimengxiaole** [comment]
那就是在项目中集成了soter，在支持的机型中，即使是带屏下指纹的手机，都可以实现微信指纹支付的效果？！

**Comment by liuxb-tofu** [comment]
不是的，soter只提供屏下指纹的位置，不提供修改厂商指纹界面的能力
