### ISSUE TITLE
人脸识别认证失败open failed, reason: SoterCoreResult{errCode=1017, errMsg='face_error_vendor: code 12'}

### ISSUE THREAD

**Issue by CreamF** [Tencent/soter#52]
open failed, reason: SoterCoreResult{errCode=1017, errMsg='face_error_vendor: code 12'}

**Comment by liuxb-tofu** [comment]
https://github.com/Tencent/soter/issues/34
看下是否是一样的问题

**Comment by CreamF** [comment]
不是同一个问题
hy: lowest level return onAuthenticationError

**Comment by CreamF** [comment]
private static FaceManager.AuthenticationCallback wrapCallback(
            final AuthenticationCallback callback) {
        return new FaceManager.AuthenticationCallback() {
            @Override
            public void onAuthenticationError(int errMsgId, CharSequence errString) {
                SLogger.d(TAG, "hy: lowest level return onAuthenticationError");
                callback.onAuthenticationError(errMsgId, errString);
            }

**Comment by CreamF** [comment]
![image](https://user-images.githubusercontent.com/12572129/78787671-4b859380-79dd-11ea-906c-375255097469.png)

**Comment by CreamF** [comment]
<img width="1052" alt="截屏2020-04-08 下午9 08 48" src="https://user-images.githubusercontent.com/12572129/78787861-8f789880-79dd-11ea-9c56-b4a6860fd415.png">

**Comment by CreamF** [comment]
<img width="1052" alt="截屏2020-04-08 下午9 08 48" src="https://user-images.githubusercontent.com/12572129/78788440-660c3c80-79de-11ea-8fe0-3948567e2e26.png">

**Comment by CreamF** [comment]
<img width="1052" alt="截屏2020-04-08 下午9 08 48" src="https://user-images.githubusercontent.com/12572129/78788559-9358ea80-79de-11ea-96f9-742ef715cf32.png">
