### ISSUE TITLE
人脸识别目前哪一款手机可以正常识别，mate20 和mate 30 都识别不了，有问题#52

### ISSUE THREAD

**Issue by CreamF** [Tencent/soter#53]

**Comment by liuxb-tofu** [comment]
mate20、mate30只有最高端的pro那一款带3d摄像头的是支持的，另外还设有finderx和nex系列也支持

**Comment by huma8848888** [comment]
> mate20、mate30只有最高端的pro那一款带3d摄像头的是支持的，另外还设有finderx和nex系列也支持

nex全系都支持吗

**Comment by SheepYang1993** [comment]
@liuxb-tofu 请问下HUAWEI Mate 30 Pro 5G支持人脸识别吗？
https://www.vmall.com/product/10086775311605.html
