### ISSUE TITLE
麻烦问下有没有可以感知设备新增指纹的api？

### ISSUE THREAD

**Issue by xyTianZhao** [Tencent/soter#58]
当设备新增指纹时，之前授权的指纹需要失效，重新使用密码进行验证后，在重新授权指纹认证。我看目前好像没有相关API？

**Comment by liuxb-tofu** [comment]
不能，但是当用户使用新指纹的时候，可以通过fid感知到

**Comment by xyTianZhao** [comment]
所以现在只能授权时候用的那个手指，验证的时候就只能用这个手指了，用其他手指验证，就相当于是新的指纹了。如果要感知新增指纹的话，就得把现存的fid都拿到，然后做对比，才可以知道当前指纹是否是新增的。是我理解的这样吗？

**Comment by liuxb-tofu** [comment]
是的
