### ISSUE TITLE
iOS平台上，SOTER客户端解决方案有了么

### ISSUE THREAD

**Issue by guoxiaobai** [Tencent/soter#72]
问一下，看文档上说 iOS平台上，SOTER也将提供客户端demo程序解决方案，现在有提供ios的解决方案么

**Comment by liuxb-tofu** [comment]
没有

**Comment by developer-zsg** [comment]
> 没有

再問一遍，現在有IOS的解決方案了嗎？或者你們目前是怎麼解決IOS端的？
