### ISSUE TITLE
关于soter SDK 2.0.6版本问题

### ISSUE THREAD

**Issue by dengtuo** [Tencent/soter#85]
腾讯开发同学： 
       你好，我是58的Android开发同学。这次想咨询一下关于soter SDK的事情。我们使用2.0.5版本遇到一些手机在启动的时候卡顿，排查原因是 SyncJob 里面的锁等待，阻塞主线程了。
       我的前同事在git issues沟通过，给出来结论是2.0.6版本进行修复此问题。目前我们在APP启动的时候进行初始化soter SDK，所以我想咨询个问题：
        当前2.0.6版本没有在git上看到release版本号，是否2.0.6 就是测试之后最终release版本号。
谢谢。

**Comment by yexuan910812** [comment]
2.0.6 has already uploaded to maven, you can try it directly. Will update readme and sourcecode later
