### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by lolkt** [Tencent/soter#87]
Could not GET 'https://dl.bintray.com/tencent-soter/maven/com/tencent/soter/soter-core/2.0.0/soter-core-2.0.0.pom'. Received status code 403 from server: Forbidden
Enable Gradle 'offline mode' and sync project

2021年2月3日，JFrog宣布将关闭Bintray和JCenter。计划在2022年2月完全关闭。
2021年5月1日，Bintray和JCenter将不再是可浏览的

请问有其他镜像可以下载吗？

**Comment by liuxb-tofu** [comment]
已更新: https://github.com/Tencent/soter#%E6%B7%BB%E5%8A%A0gradle%E4%BE%9D%E8%B5%96
